EXP 1 

Aim: Creation of arrays using numpy

In [3]:
#Name: Mayuri Rathod
#Roll no: 51
#subject: ET -1
#Sec: C
#Date: 20/08/2025


In [4]:
import numpy as np

In [11]:
#creating 1D array. (square bracket in round = array)(square bracket=tuple)
a1=np.array([60,10,50,10])

In [12]:
a1

array([60, 10, 50, 10])

In [13]:
#creating 2D array 
a2 = np.array([[11,22,18,24],[41,35,40,55]])

In [14]:
a2

array([[11, 22, 18, 24],
       [41, 35, 40, 55]])

In [15]:
#creating 2D array using matrix
a3=np.matrix('11,23;33,45;67,78')
print(a3)


[[11 23]
 [33 45]
 [67 78]]


In [16]:
# Create array of 25 random integers between 20 and 23 (inclusive)
arr = np.random.randint(20, 24, size=25)
print(arr)

[23 21 23 21 22 23 20 21 21 22 22 20 21 20 20 22 20 20 23 20 23 21 20 20
 23]
